name: Live
on: [push]

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get update && sudo apt-get install -y ffmpeg
      - run: |
          ffmpeg -re -i "X4jT5_LU0Ww.mp4" -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -f flv "rtmp://a.rtmp.youtube.com/live2/e7cv-4rbr-8cm6-1dut-2t9a"
